### ISSUE TITLE
Error viewing emails on inboxkitten.com TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by darshil5p** [uilicious/inboxkitten#17]
i am unable to get mails from a sender. However it only happens from that particular domain, i can see emails from everyone else. In the browser console it says this : 
TypeError: Cannot read property 'split' of undefined
    at s.formatName (message_list.vue:124)
    at message_list.vue?71dd:1
    at s.Nt [as _l] (vue.esm.js:3705)
    at s.render (message_list.vue?71dd:1)
    at s.e._render (vue.esm.js:4544)
    at s.<anonymous> (vue.esm.js:2788)
    at Ot.get (vue.esm.js:3142)
    at Ot.run (vue.esm.js:3219)
    at Ht (vue.esm.js:2981)
    at Array.<anonymous> (vue.esm.js:1837)
Ie @ vue.esm.js:1741

This is a bug on inboxkitten.com itself and not on any custom domain

**Comment by jmtiong** [comment]
@darshil5p are you able to share that particular domain? if not it will be quite hard to resolve it

**Comment by darshil5p** [comment]
Sure , Playerauctions.com signup and they'll send an activation email . That's it. The issue will be displayed in the console

**Comment by jmtiong** [comment]
@darshil5p thanks for the long wait!! The issue is with the email address of the sender, when it does not have a formatted name like `PlayerAuction <noreply@playerauction.com>` but instead it is just `noreply@playerauction.com` it will throw errors as it cannot split it properly

The fix is https://github.com/uilicious/inboxkitten/pull/23 :) please try again!!

**Comment by darshil5p** [comment]
Awesome! Thanks a lot gonna try it out now
