### ISSUE TITLE
My Email Hack Using https://inboxkitten.com/

### ISSUE THREAD

**Issue by helpmeplzhelp** [uilicious/inboxkitten#57]
I have brought to your notice that my official Gmail account (ravish.gupta.ece@gmail.com and ravishguptaece@gmail.com) was hacked
from unknown sources. Even my recovery email id and phone number have been changed by unknown sources. plz help me plz

**Comment by PicoCreator** [comment]
I am really sorry to hear this - we have documented the issue here : https://uilicious.com/blog/psa-inboxkitten-will-be-blocking-no-reply-google/ - including what you can do.

In general your best hope is to contact google somehow, as this sort of attack is an exploit on how easy it is to "change your email" to any source (hotmail for example could be used as an inboxkitten substitute).

We have implemented measures to limit this attack pattern specifically through our platform, but this does little but make it more troublesome for the attacker, as they can just change the mail provider they use in the attack.
